POST http://localhost:8080/adresse
X-XSRF-TOKEN: d6c14f6f-9589-4094-925a-40e845bd4a02
Content-Type: application/json

{
  "commune": "Montpellier",
  "codePostal": 34000,
  "numero": 40,
  "voie": "Avenue de Fes"
}

###
POST http://localhost:8080/adresse
X-XSRF-TOKEN: d6c14f6f-9589-4094-925a-40e845bd4a02
Content-Type: application/json

{
  "commune": "Castelnau-le-Lez",
  "codePostal": 34170,
  "numero": 155,
  "voie": "Avenue du Devois"
}

###
GET http://localhost:8080/adresse/find
X-XSRF-TOKEN: d6c14f6f-9589-4094-925a-40e845bd4a02
Content-Type: application/json

