
POST http://localhost:8080/covoiturages
Content-Type: application/json
JWT-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwicGFzc3dvcmQiOiJ7YmNyeXB0fSQyYSQxMCR3UmRpTzc2YU5TUy81bkw4cERDNUJ1bU56czQvMnd1czMuL0tEUmFIckhkNVhtcDJGSnQ2ZSIsInJvbGVzIjpbIkNPTExBQk9SQVRFVVIiLCJBRE1JTklTVFJBVEVVUiJdLCJlbWFpbCI6ImRpamlhbGVpQ29sbEFkbWluQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiQ29sbEFkbWluIiwiZXhwIjoxNjkzNDkzNjQyfQ.cqfbJxJlkp3naSQCZQhu3c16yhZje7c_cL2vuvhq5sc


{
  "nombrePlacesRestantes": 4,
  "dateDepart": "2023-09-02T17:05:00"

}

###

POST http://localhost:8080/covoiturages/testCreatePassageur
Content-Type: application/json
JWT-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwicGFzc3dvcmQiOiJ7YmNyeXB0fSQyYSQxMCR3UmRpTzc2YU5TUy81bkw4cERDNUJ1bU56czQvMnd1czMuL0tEUmFIckhkNVhtcDJGSnQ2ZSIsInJvbGVzIjpbIkNPTExBQk9SQVRFVVIiLCJBRE1JTklTVFJBVEVVUiJdLCJlbWFpbCI6ImRpamlhbGVpQ29sbEFkbWluQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiQ29sbEFkbWluIiwiZXhwIjoxNjkzNDkzNjQyfQ.cqfbJxJlkp3naSQCZQhu3c16yhZje7c_cL2vuvhq5sc


{
  "userId": 5,
  "conId": 2
}


### USER 5
POST http://localhost:8080/covoiturages/create
X-XSRF-TOKEN: 4f2ed8de-4381-4e78-9eca-0d4168abb148
Content-Type: application/json
JWT-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1IiwicGFzc3dvcmQiOiJ7YmNyeXB0fSQyYSQxMCRML0VRWjN3WW1haFNta3oxSzhzZjhlYzdGbC8vMWVIRXlLbWhYTmdlZnhBYlR3TUlaS3hvbSIsInJvbGVzIjpbIkNPTExBQk9SQVRFVVIiXSwiZW1haWwiOiJjb2xsYWJvcmF0ZXVyNUBnZXN0aXQuZnIiLCJ1c2VybmFtZSI6IkNvbGxhYjUiLCJleHAiOjE2OTM1Nzc5NDB9.8XjrK7NuzSKt-5OXN654U3FgHeK97fJRx4SvM3vb5u4

{
  "nombrePlacesRestantes": 4,
  "dureeTrajet": 1,
  "distanceKm": 1350,
  "dateDepart": "2023-09-01",
  "adresseDepartId": 1,
  "adresseArriveeID":2,
  "organisateurId": 6,
  "passagers": null,
  "vehiculePersoId": 2
}

### USER 5
GET http://localhost:8080/RestTemplate/getAllCovoiturages
Content-Type: application/json

### USER 6
POST http://localhost:8080/RestTemplate/addCovoiturage
Content-Type: application/json
{
  "nombrePlacesRestantes": 4,
  "dateDepart": "2023-09-02T17:05:00"

}
