
###
GET http://localhost:8080/marque
X-XSRF-TOKEN: d6c14f6f-9589-4094-925a-40e845bd4a02
Content-Type: application/json

###
POST http://localhost:8080/marque
X-XSRF-TOKEN: d6c14f6f-9589-4094-925a-40e845bd4a02
Content-Type: application/json

{
  "nom" : " "
}