###
GET http://localhost:8080/reservation
X-XSRF-TOKEN: 4f2ed8de-4381-4e78-9eca-0d4168abb148
Content-Type: application/json


###
POST http://localhost:8080/reservation/create
X-XSRF-TOKEN: 4f2ed8de-4381-4e78-9eca-0d4168abb148
Content-Type: application/json

{
  "userId": 4,
  "vehiculeServiceId":1,
  "dateHeureDepart":"2023-09-01T17:05:00",
  "dateHeureRetour":"2023-09-11T08:50:00"
}

###
POST http://localhost:8080/reservation/modify
X-XSRF-TOKEN: 4f2ed8de-4381-4e78-9eca-0d4168abb148
Content-Type: application/json

{
  "userId": 4,
  "vehiculeServiceId":1,
  "dateHeureDepart":"2023-09-01T18:05:00",
  "dateHeureRetour":"2023-09-11T08:50:00",
  "oldResId": 3
}