###
GET http://localhost:8080/reservation
X-XSRF-TOKEN: 4f2ed8de-4381-4e78-9eca-0d4168abb148
Content-Type: application/json
JWT-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1IiwicGFzc3dvcmQiOiJ7YmNyeXB0fSQyYSQxMCRML0VRWjN3WW1haFNta3oxSzhzZjhlYzdGbC8vMWVIRXlLbWhYTmdlZnhBYlR3TUlaS3hvbSIsInJvbGVzIjpbIkNPTExBQk9SQVRFVVIiXSwiZW1haWwiOiJjb2xsYWJvcmF0ZXVyNUBnZXN0aXQuZnIiLCJ1c2VybmFtZSI6IkNvbGxhYjUiLCJleHAiOjE2OTM1Nzc5NDB9.8XjrK7NuzSKt-5OXN654U3FgHeK97fJRx4SvM3vb5u4


###
GET http://localhost:8080/reservation/upcoming
X-XSRF-TOKEN: 4f2ed8de-4381-4e78-9eca-0d4168abb148
Content-Type: application/json
JWT-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxNSIsInBhc3N3b3JkIjoie2JjcnlwdH0kMmEkMTAkU0VVUXVZNU1VL2EwRGhRUUc4TE1tLmowdHNWR2pFeG9JejFlY2Z5c1ZrRzluODhISmVkaHEiLCJyb2xlcyI6WyJDT0xMQUJPUkFURVVSIl0sImVtYWlsIjoiY29sbGFib3JhdGV1cjFAZ2VzdGl0LmZyIiwidXNlcm5hbWUiOiJDb2xsYWIxIiwiZXhwIjoxNjkzNTY5MTg2fQ.vbTOfMZmRjtaA27HmrJl9hiUXH6thKKQzN0m2tZrazM
###
GET http://localhost:8080/reservation/past
X-XSRF-TOKEN: 4f2ed8de-4381-4e78-9eca-0d4168abb148
Content-Type: application/json
JWT-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxNSIsInBhc3N3b3JkIjoie2JjcnlwdH0kMmEkMTAkU0VVUXVZNU1VL2EwRGhRUUc4TE1tLmowdHNWR2pFeG9JejFlY2Z5c1ZrRzluODhISmVkaHEiLCJyb2xlcyI6WyJDT0xMQUJPUkFURVVSIl0sImVtYWlsIjoiY29sbGFib3JhdGV1cjFAZ2VzdGl0LmZyIiwidXNlcm5hbWUiOiJDb2xsYWIxIiwiZXhwIjoxNjkzNTY5MTg2fQ.vbTOfMZmRjtaA27HmrJl9hiUXH6thKKQzN0m2tZrazM


###
POST http://localhost:8080/reservation/create
X-XSRF-TOKEN: 4f2ed8de-4381-4e78-9eca-0d4168abb148
Content-Type: application/json
JWT-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1IiwicGFzc3dvcmQiOiJ7YmNyeXB0fSQyYSQxMCRML0VRWjN3WW1haFNta3oxSzhzZjhlYzdGbC8vMWVIRXlLbWhYTmdlZnhBYlR3TUlaS3hvbSIsInJvbGVzIjpbIkNPTExBQk9SQVRFVVIiXSwiZW1haWwiOiJjb2xsYWJvcmF0ZXVyNUBnZXN0aXQuZnIiLCJ1c2VybmFtZSI6IkNvbGxhYjUiLCJleHAiOjE2OTM1Nzc5NDB9.8XjrK7NuzSKt-5OXN654U3FgHeK97fJRx4SvM3vb5u4

{
  "userId": 5,
  "vehiculeServiceId":1,
  "dateHeureDepart":"2023-09-19T17:05:00",
  "dateHeureRetour":"2023-09-20T08:50:00"
}

###
POST http://localhost:8080/reservation/modify?resId=4
X-XSRF-TOKEN: 4f2ed8de-4381-4e78-9eca-0d4168abb148
Content-Type: application/json
JWT-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxNCIsInBhc3N3b3JkIjoie2JjcnlwdH0kMmEkMTAkWG44c2tOYjZVa3BsSFRHWWp3bXB3ZXpJTE1pMXdQR0k0NmJxZjdyd1JPd0d6YnAxNnQwZEciLCJyb2xlcyI6WyJDT0xMQUJPUkFURVVSIiwiQURNSU5JU1RSQVRFVVIiXSwiZW1haWwiOiJkaWppYWxlaUNvbGxBZG1pbkBnbWFpbC5jb20iLCJ1c2VybmFtZSI6IkNvbGxBZG1pbiIsImV4cCI6MTY5MzE1MDA5OX0.juWSTv77L_SUTB_DKJlAQWyUSGFqNdv07_5EAkz1gvQ

{
  "userId": 14,
  "vehiculeServiceId":2,
  "dateHeureDepart":"2023-09-04T18:05:00",
  "dateHeureRetour":"2023-09-12T08:50:00"
}

###
POST http://localhost:8080/reservation/delete?resId=5
X-XSRF-TOKEN: 4f2ed8de-4381-4e78-9eca-0d4168abb148
Content-Type: application/json
JWT-TOKEN:eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxNCIsInBhc3N3b3JkIjoie2JjcnlwdH0kMmEkMTAkWG44c2tOYjZVa3BsSFRHWWp3bXB3ZXpJTE1pMXdQR0k0NmJxZjdyd1JPd0d6YnAxNnQwZEciLCJyb2xlcyI6WyJDT0xMQUJPUkFURVVSIiwiQURNSU5JU1RSQVRFVVIiXSwiZW1haWwiOiJkaWppYWxlaUNvbGxBZG1pbkBnbWFpbC5jb20iLCJ1c2VybmFtZSI6IkNvbGxBZG1pbiIsImV4cCI6MTY5MzE1MDA5OX0.juWSTv77L_SUTB_DKJlAQWyUSGFqNdv07_5EAkz1gvQ


{
  "userId": 12,
  "vehiculeServiceId":1,
  "dateHeureDepart":"2023-09-01T18:05:00",
  "dateHeureRetour":"2023-09-11T08:50:00"
}