GET http://localhost:8080/utilisateur/findNom
X-XSRF-TOKEN: d6c14f6f-9589-4094-925a-40e845bd4a02
Content-Type: application/json

###
POST localhost:8080/utilisateur/create
X-XSRF-TOKEN: d6c14f6f-9589-4094-925a-40e845bd4a02
Content-Type: application/json

{
  "nom": "nom7",
  "email": "nom7@nom.com",
  "motDePasse": "1234",
  "roles": ["COLLABORATEUR"]
}
###
POST localhost:8080/utilisateur/modify?idUser=5
X-XSRF-TOKEN: d6c14f6f-9589-4094-925a-40e845bd4a02
Content-Type: application/json

{
  "nom": "nom6",
  "email":"nom5@nom.com" ,
  "motDePasse": "1236",
  "roles": ["COLLABORATEUR"],
  "dateNonValide": "2023-01-01"
}
###
GET http://localhost:8080/utilisateur/disable?idUser=5
X-XSRF-TOKEN: d6c14f6f-9589-4094-925a-40e845bd4a02
Content-Type: application/json



###
GET localhost:8080/admin/vehiculeservice/list
Content-Type: application/json
JWT-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI3IiwicGFzc3dvcmQiOiJ7YmNyeXB0fSQyYSQxMCRnT09YQnQwUE45SjZ5djFaTjMyU25PRzFSUEJuMXEweWl4b2hTT2dRVlBDZUYxbEdOaEZFYSIsInJvbGVzIjpbIkFETUlOSVNUUkFURVVSIl0sImlkIjo3LCJ1c2VybmFtZSI6ImRpamlhbGVpIiwiZXhwIjoxNjkxNDU1NzUxfQ.Ncxny1P7ymPhj6XILC7ZX1EWd3c-H7IZjELKDGzZ4Ls


###

POST localhost:8080/signout
Content-Type: application/json

###
POST localhost:8080/utilisateur/create
Content-Type: application/json

{
  "nom": "CollAdmin",
  "email": "dijialeiCollAdmin@gmail.com",
  "motDePasse": "CollAdmin",
  "roles": ["COLLABORATEUR","ADMINISTRATEUR"]
}



###
GET localhost:8080/admin/vehiculeservice/list
Content-Type: application/json


###

POST localhost:8080/signout
Content-Type: application/json
JWT-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxNCIsInBhc3N3b3JkIjoie2JjcnlwdH0kMmEkMTAkWG44c2tOYjZVa3BsSFRHWWp3bXB3ZXpJTE1pMXdQR0k0NmJxZjdyd1JPd0d6YnAxNnQwZEciLCJyb2xlcyI6WyJDT0xMQUJPUkFURVVSIiwiQURNSU5JU1RSQVRFVVIiXSwiZW1haWwiOiJkaWppYWxlaUNvbGxBZG1pbkBnbWFpbC5jb20iLCJ1c2VybmFtZSI6IkNvbGxBZG1pbiIsImV4cCI6MTY5MzQ3NzQwOH0.pXvt9Potn909B8VE79Sz11EbFcI5skxO-GQMtXTIAOg

{


}
###
POST localhost:8080/login
Content-Type: application/json

{
  "email": "dijialeiCollAdmin@gmail.com",

  "motDePasse": "CollAdmin"

}

###
POST localhost:8080/getidbyjwt
Content-Type: application/json
JWT-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI3IiwicGFzc3dvcmQiOiJ7YmNyeXB0fSQyYSQxMCRnT09YQnQwUE45SjZ5djFaTjMyU25PRzFSUEJuMXEweWl4b2hTT2dRVlBDZUYxbEdOaEZFYSIsInJvbGVzIjpbIkFETUlOSVNUUkFURVVSIl0sInVzZXJuYW1lIjoiZGlqaWFsZWkiLCJleHAiOjE2OTIyNjI3OTN9.UXpvW-HXheCGNBqBa1NPeBEAbqMMTDdw_TEEZcEEnUQ

{


}