POST 127.0.0.1:8080/admin/vehiculeservice/create
Content-Type: application/json
X-XSRF-TOKEN: 4d57638b-da81-4fdb-b36a-5b766ce4d9fd

{

    "modele": "Megane",
    "nombreDePlaceDisponibles":5 ,
    "immatriculation": "T123456",
    "photoURL": "http://www.diginamic.fr/photo-car.jpg",
    "emissionCO2": 160,
    "motorisation": "HYBRIDE" ,
    "statut": "EN_SERVICE",
    "categorie": "MICRO_URBAINES"
}

### TOKEN ADMIN
GET 127.0.0.1:8080/admin/vehiculeservice/list
Content-Type: application/json
X-XSRF-TOKEN: 4d57638b-da81-4fdb-b36a-5b766ce4d9fd
JWT-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI3IiwicGFzc3dvcmQiOiJ7YmNyeXB0fSQyYSQxMCRnT09YQnQwUE45SjZ5djFaTjMyU25PRzFSUEJuMXEweWl4b2hTT2dRVlBDZUYxbEdOaEZFYSIsInJvbGVzIjpbIkFETUlOSVNUUkFURVVSIl0sInVzZXJuYW1lIjoiZGlqaWFsZWkiLCJleHAiOjE2OTMxMjk0MjJ9.Spnumw4PSd7HFsroUlX-gAMdTSXoDkI1feHEp6JO-4U



###
POST 127.0.0.1:8080/admin/vehiculeservice/modify
Content-Type: application/json
X-XSRF-TOKEN: 4d57638b-da81-4fdb-b36a-5b766ce4d9fd

{
  "id": 1,
  "modele": "Megane",
  "nombreDePlaceDisponibles":5 ,
  "immatriculation": "ù123456",
  "photoURL": "http://www.diginamic.fr/photo-car.jpg",
  "emissionCO2": 160,
  "motorisation": "HYBRIDE" ,
  "statut": "EN_SERVICE",
  "categorie": "MICRO_URBAINES"
}

### TOKEN ADMIN
GET 127.0.0.1:8080/admin/vehiculeservice/delete?id=1
Content-Type: application/json
X-XSRF-TOKEN: 4d57638b-da81-4fdb-b36a-5b766ce4d9fd
JWT-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI3IiwicGFzc3dvcmQiOiJ7YmNyeXB0fSQyYSQxMCRnT09YQnQwUE45SjZ5djFaTjMyU25PRzFSUEJuMXEweWl4b2hTT2dRVlBDZUYxbEdOaEZFYSIsInJvbGVzIjpbIkFETUlOSVNUUkFURVVSIl0sInVzZXJuYW1lIjoiZGlqaWFsZWkiLCJleHAiOjE2OTMxMjk0MjJ9.Spnumw4PSd7HFsroUlX-gAMdTSXoDkI1feHEp6JO-4U
