POST 127.0.0.1:8080/admin/vehiculeservice/create
Content-Type: application/json
X-XSRF-TOKEN: 4d57638b-da81-4fdb-b36a-5b766ce4d9fd

{

    "modele": "Megane",
    "nombreDePlaceDisponibles":5 ,
    "immatriculation": "D123456",
    "photoURL": "http://www.diginamic.fr/photo-car.jpg",
    "emissionCO2": 160,
    "motorisation": "HYBRIDE" ,
    "statut": "EN_SERVICE",
    "categorie": "MICRO_URBAINES"
}

### TOKEN ADMIN
GET 127.0.0.1:8080/admin/vehiculeservice/list
Content-Type: application/json
X-XSRF-TOKEN: 4d57638b-da81-4fdb-b36a-5b766ce4d9fd
JWT-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI3IiwicGFzc3dvcmQiOiJ7YmNyeXB0fSQyYSQxMCRnT09YQnQwUE45SjZ5djFaTjMyU25PRzFSUEJuMXEweWl4b2hTT2dRVlBDZUYxbEdOaEZFYSIsInJvbGVzIjpbIkFETUlOSVNUUkFURVVSIl0sInVzZXJuYW1lIjoiZGlqaWFsZWkiLCJleHAiOjE2OTMxMjk0MjJ9.Spnumw4PSd7HFsroUlX-gAMdTSXoDkI1feHEp6JO-4U



###
POST 127.0.0.1:8080/admin/vehiculeservice/modify
X-XSRF-TOKEN: 4f2ed8de-4381-4e78-9eca-0d4168abb148
Content-Type: application/json
JWT-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxNCIsInBhc3N3b3JkIjoie2JjcnlwdH0kMmEkMTAkWG44c2tOYjZVa3BsSFRHWWp3bXB3ZXpJTE1pMXdQR0k0NmJxZjdyd1JPd0d6YnAxNnQwZEciLCJyb2xlcyI6WyJDT0xMQUJPUkFURVVSIiwiQURNSU5JU1RSQVRFVVIiXSwiZW1haWwiOiJkaWppYWxlaUNvbGxBZG1pbkBnbWFpbC5jb20iLCJ1c2VybmFtZSI6IkNvbGxBZG1pbiIsImV4cCI6MTY5MzE1MDA5OX0.juWSTv77L_SUTB_DKJlAQWyUSGFqNdv07_5EAkz1gvQ

{
  "id": 1,
  "modele": "Megane",
  "nombreDePlaceDisponibles":5 ,
  "immatriculation": "G123456",
  "photoURL": "http://www.diginamic.fr/photo-car.jpg",
  "emissionCO2": 160,
  "motorisation": "HYBRIDE" ,
  "statut": "EN_SERVICE",
  "categorie": "MICRO_URBAINES"
}

### TOKEN ADMIN
GET 127.0.0.1:8080/admin/vehiculeservice/delete?id=1
Content-Type: application/json
X-XSRF-TOKEN: 4d57638b-da81-4fdb-b36a-5b766ce4d9fd
JWT-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI3IiwicGFzc3dvcmQiOiJ7YmNyeXB0fSQyYSQxMCRnT09YQnQwUE45SjZ5djFaTjMyU25PRzFSUEJuMXEweWl4b2hTT2dRVlBDZUYxbEdOaEZFYSIsInJvbGVzIjpbIkFETUlOSVNUUkFURVVSIl0sInVzZXJuYW1lIjoiZGlqaWFsZWkiLCJleHAiOjE2OTMxMjk0MjJ9.Spnumw4PSd7HFsroUlX-gAMdTSXoDkI1feHEp6JO-4U
