insert into marque (nom) values('Peugeot');
insert into marque (nom) values('Renault');
insert into marque (nom) values('Citroën');
insert into marque (nom) values('Fiat');
insert into marque (nom) values('Dacia');
insert into marque (nom) values('Toyota');
insert into marque (nom) values('BMW');
insert into marque (nom) values('Hyundai');
insert into marque (nom) values('Kia');
insert into marque (nom) values('Volkswagen');
insert into marque (nom) values('Skoda');
insert into marque (nom) values('Seat');
insert into modele (nom, marque_id) values('208',1);
insert into modele (nom, marque_id) values('2008',1);
insert into modele (nom, marque_id) values('308',1);
insert into modele (nom, marque_id) values('3008',1);
insert into modele (nom, marque_id) values('508',1);
insert into modele (nom, marque_id) values('5008',1);
insert into modele (nom, marque_id) values('Clio',2);
insert into modele (nom, marque_id) values('Megane',2);
insert into modele (nom, marque_id) values('Twingo',2);
insert into modele (nom, marque_id) values('C3',3);
insert into modele (nom, marque_id) values('C4',3);
insert into modele (nom, marque_id) values('C5',3);
insert into modele (nom, marque_id) values('500',4);
insert into modele (nom, marque_id) values('500X',4);
insert into modele (nom, marque_id) values('Panda',4);
insert into modele (nom, marque_id) values('Duster',5);
insert into modele (nom, marque_id) values('Spring',5);
insert into modele (nom, marque_id) values('Yaris',6);
insert into modele (nom, marque_id) values('Corolla',6);
insert into modele (nom, marque_id) values('Rav4',6);
insert into modele (nom, marque_id) values('Serie 3',7);
insert into modele (nom, marque_id) values('Serie 5',7);
insert into modele (nom, marque_id) values('Serie 7',7);
insert into modele (nom, marque_id) values('i20',8);
insert into modele (nom, marque_id) values('i30',8);
insert into modele (nom, marque_id) values('Ceed',9);
insert into modele (nom, marque_id) values('Niro',9);
insert into modele (nom, marque_id) values('Sportage',9);
insert into modele (nom, marque_id) values('Golf',10);
insert into modele (nom, marque_id) values('Polo',10);
insert into modele (nom, marque_id) values('Fabia',11);
insert into modele (nom, marque_id) values('Octavia',11);
insert into modele (nom, marque_id) values('Leon',12);
insert into modele (nom, marque_id) values('Cupra',12);
insert into commune (nom, code_postal) values('Montpellier',34000);
insert into commune (nom, code_postal) values('Nîmes',30000);
insert into commune (nom, code_postal) values('Marseille',13000);
insert into adresse (numero, voie, commune_id) values(12, 'rue du Faubourg de Boutonnet', 1);
insert into adresse (numero, voie, commune_id) values(1065, 'Avenue du Père Soulas', 1);
insert into adresse (numero, voie, commune_id) values(35, 'Boulevard Gambetta', 2);
insert into adresse (numero, voie, commune_id) values(13, 'Avenue Georges Pompidou', 2);
insert into adresse (numero, voie, commune_id) values(2, 'Quai du Port', 3);
insert into adresse (numero, voie, commune_id) values(15, 'Avenue du Prado', 3);
