### LOGIN COLLABORATEUR

POST localhost:8080/login
Content-Type: application/json

{
  "email": "collaborateur1@gestit.fr",
  "motDePasse": "passCollab1"
}

### LOGIN ADMINISTRATEUR

POST localhost:8080/login
Content-Type: application/json

{
  "email": "administrateur1@gestit.fr",
  "motDePasse": "passAdmin1"
}


###

POST localhost:8080/signout
Content-Type: application/json
JWT-TOKEN: "votre JWT-TOKEN reçu lors du logIn"