### LOGIN COLLABORATEUR
POST localhost:8080/login
Content-Type: application/json

{
  "email": "collaborateur1@gestit.fr",
  "motDePasse": "passCollab1"
}

### LOGIN ADMINISTRATEUR
POST localhost:8080/login
Content-Type: application/json

{
  "email": "administrateur1@gestit.fr",
  "motDePasse": "passAdmin1"
}


###

POST localhost:8080/signout
Content-Type: application/json
JWT-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzIiwicGFzc3dvcmQiOiJ7YmNyeXB0fSQyYSQxMCR3cHEubVRJaUthMEtuM1dLR0RkQ2p1YW1LVXd4Wi9EdS51R01rVkJzOHB3QXBXaXNuTTVXeSIsInJvbGVzIjpbIkNPTExBQk9SQVRFVVIiXSwiZW1haWwiOiJjb2xsYWJvcmF0ZXVyM0BnZXN0aXQuZnIiLCJ1c2VybmFtZSI6IkNvbGxhYjMiLCJleHAiOjE2OTM1ODM5MzN9.oqpR_FH9OIlIkSewehAc1vyvGIZNPjE80qaMOuF_3rE