POST 127.0.0.1:8080/vehiculeperso/create
Content-Type: application/json
JWT-TOKEN: "votre JWT-TOKEN reçu lors du logIn"

{

  "modele" : "208",
  "nombreDePlaceDisponibles": 5,
  "immatriculation":  "test423456"

}

###

GET 127.0.0.1:8080/vehiculeperso/list
Content-Type: application/json
JWT-TOKEN: "votre JWT-TOKEN reçu lors du logIn"

###
POST 127.0.0.1:8080/vehiculeperso/modify
Content-Type: application/json
JWT-TOKEN: "votre JWT-TOKEN reçu lors du logIn"

{
  "id": 1,
  "modele" : "308",
  "nombreDePlaceDisponibles": 4,
  "immatriculation":  "modify12345"
}

###

GET 127.0.0.1:8080/vehiculeperso/delete?id=1
Content-Type: application/json
JWT-TOKEN: "votre JWT-TOKEN reçu lors du logIn"

###

