POST 127.0.0.1:8080/vehiculeperso/create
Content-Type: application/json
JWT-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwicGFzc3dvcmQiOiJ7YmNyeXB0fSQyYSQxMCR3UmRpTzc2YU5TUy81bkw4cERDNUJ1bU56czQvMnd1czMuL0tEUmFIckhkNVhtcDJGSnQ2ZSIsInJvbGVzIjpbIkNPTExBQk9SQVRFVVIiLCJBRE1JTklTVFJBVEVVUiJdLCJlbWFpbCI6ImRpamlhbGVpQ29sbEFkbWluQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiQ29sbEFkbWluIiwiZXhwIjoxNjkzNDkzNjQyfQ.cqfbJxJlkp3naSQCZQhu3c16yhZje7c_cL2vuvhq5sc


{

  "modele" : "208",
  "nombreDePlaceDisponibles": 5,
  "immatriculation":  "test423456",
  "userId": 3
}

###

GET 127.0.0.1:8080/vehiculeperso/list?userId=3
Content-Type: application/json

###
POST 127.0.0.1:8080/vehiculeperso/modify
Content-Type: application/json
X-XSRF-TOKEN: "votre JWT-TOKEN reçu lors du logIn"

{
  "id": 10,
  "modele" : "308",
  "nombreDePlaceDisponibles": 4,
  "immatriculation":  "T23456",
  "userId": 3
}

###

GET 127.0.0.1:8080/vehiculeperso/delete?id=2&userId=3
Content-Type: application/json
JWT-TOKEN: "votre JWT-TOKEN reçu lors du logIn"

###

